### ISSUE TITLE
建议所有项目采用同一个版本VS

### ISSUE THREAD

**Issue by sunflover** [redrains/DuiLib_Redrain#11]
我发现duilib采用VS2008，而Demo则有2010，2012，这样子工程高转低蛮麻烦的，希望把VS版本统一VS2008或VS2013都行。

**Comment by sunflover** [comment]
各个Demo编译也是一堆问题，很头大。希望发布前能在纯净环境测试编译通过。

**Comment by redrains** [comment]
Duilib本身的项目配置我都专门仔细改过了，不过附加的那几个demo我只是随意写的，并且由于不同情况用了不同的VS版本，但是那几个demo都比较简单，需要的话自己重新配个工程或者索性直接看cpp代码就可以了
