### ISSUE TITLE
kuGou 示例项目部分资源加载失败

### ISSUE THREAD

**Issue by nmgwddj** [redrains/DuiLib_Redrain#21]
![2017-03-01_000400](https://cloud.githubusercontent.com/assets/13995319/23413149/d05d4b7e-fe12-11e6-94b0-e48917bbcccf.png)

如上图所示，我自己参照了您的代码自己写了一个 treenode  的案例，也是有部分资源加载不了，请教是什么原因？

```
<?xml version="1.0" encoding="UTF-8"?>
<Window>
    <ProblemListGroup menu="true" inset="50,0,0,0" height="50" bkcolor="#FFc1c1c1"
                      itemattr="valign=&quot;vcenter&quot; textpadding=&quot;5,0,0,0&quot; font=&quot;2&quot;" 
                      folderattr="padding=&quot;0,6,0,0&quot; width=&quot;16&quot; height=&quot;16&quot; selectedimage=&quot;problem_list\expland_down.png&quot; normalimage=&quot;problem_list\expland_normal.png&quot;">
    </ProblemListGroup>
</Window>
<!-- inherit TreeNode -->
```

其中 `problem_list\expland_down.png` 没有被成功加载，界面上那个位置是空白的。

**Comment by redrains** [comment]
仿酷狗的例子，我已经把酷狗相关素材全部删掉了，所以自己编译的程序是看不到素材图的。我在demo里附加了一个已经集成素材的仿酷狗exe文件，可以看到包含素材的效果。
如果你使用自己的素材，需要注意自己素材指定的路径，仿酷狗素材的根目录统一都是"UI"
